sudo: false
dist: trusty
language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "nightly"
  - "pypy-5.3.1"
  - "pypy-5.4.1"
  - "pypy-5.6.0"
  - "pypy-5.7.1"
  - "pypy3-2.4.0"
  - "pypy2.7-5.8.0"
  - "pypy3.5-5.8.0"
before_install:
  - if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]] && [[ $TRAVIS_PYTHON_VERSION != "3.3" ]] && [[ $TRAVIS_PYTHON_VERSION != "pypy3-2.4.0" ]]; then pip install --upgrade pip setuptools; fi
install:
  - pip install "pkginfo<1.3"
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install twine
script: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coverage run --source=paypal setup.py test; else python setup.py test; fi
after_success: if [[ $TRAVIS_PYTHON_VERSION != "3.2" ]]; then coveralls; fi
deploy:
  provider: pypi
  user: joamag
  password:
    secure: cmQtHkRRtdxevs+6qugHTgXWVOT6gsGcKj0e/2PkNpBOEM12vx5lO2VlBs2XiZtShgJ7Y0w0haJXsRL/si/EQpNZllPT62USZWD7+r7jSbGujw6jdbmb0LtZsqptNAUy13tQo7Oe+clUuS9ciW54vuRbPTXn6VvdkD1j/mTVJ3A9nMJF44u0EuUbMV8oqYBMORcuSN4HsWLKtZj6GmFLUGs9wBT3ADeNhnub2xB0P90G7JsSzDjwelUQJsXS4dmpIvcC11HzCUh3wKjlALBZ8nLb3TyFcwII1zE70OZRi4pOdFhUtaeH6ChN/qp2jVCs6Zm+Bt3UiE0cwWb7DgAquoyG3b0oJh8f24iqB3qYH+bX6a8ikmeLv20SitwpyWi8BbSrQYI3tSpqoLzpEpkB4F6J8zci0i9pmVEqHYZ0neB/Esdm1KssXS7I5yP3mETvRkfdMFM1lXfBU2cXIp+Lg68J00er+QX/xGfPo7+EQIb/4X8gcvN0aRpBOn/AkBd+pAa3pvT21RSH9XmCEhZb2UrHd1u6zzErOS95kHS4zzt43bPkqLtEBxyC1ALCbzSayfUQ7imgpDRTVWxhKeiQWU6FiFompKQqG5Hxp3PtxoHV6IEI2kNzZmWstiRAgHZ9EyqkFYyCkM+HArXSZkMoDPhMO0iJ6IcG/f+sp/KjlAk=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "2.7"
